controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz For Gazebo

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint_gripper
      - joint_gripper_mimic
    interface_name: position

trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint_gripper
      - joint_gripper_mimic
     
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
